<?php

namespace Avxman\Rewrite\Middlewares;

use Closure;
use Illuminate\Session\Middleware\StartSession as Middleware;

class Rewrite extends Middleware
{

    public function handle($request, Closure $next)
    {
        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

}
